### ISSUE TITLE
Compilation Crash

### ISSUE THREAD

**Issue by zyz9740** [leaningtech/cheerp-meta#128] opened 2022-10-11 16:06 UTC
Maybe other one with infinite loop and printf, but this time conpilation crash occurs.

I submit the trigger directly. You can take a try.

[crash-bug-10-11.zip](https://github.com/leaningtech/cheerp-meta/files/9757856/crash-bug-10-11.zip)

**Comment by carlopi** [comment] 2022-10-12 05:39
I do reproduce, even with nightly version.
This seems to be unconnected to #127.

The raised assertion is in the register allocator, here: https://github.com/leaningtech/cheerp-compiler/blob/master/llvm/lib/CheerpUtils/Registerize.cpp#L232, but will need to be further inspected.

**Comment by carlopi** [comment] 2022-10-24 07:43
This is fixed in the currently live [nightly](https://launchpad.net/~leaningtech-dev/+archive/ubuntu/cheerp-nightly-ppa/+packages) version of Cheerp. Thanks for reporting this.

**Closed by carlopi** 2022-10-24 07:43 UTC
