### ISSUE TITLE
bit field initialize fail

### ISSUE THREAD

**Issue by zyz9740** [leaningtech/cheerp-meta#119] opened 2022-07-15 01:47 UTC
[bit_field_initialize_fail.zip](https://github.com/leaningtech/cheerp-meta/files/9117009/bit_field_initialize_fail.zip)

Please look at this bug as well,  I don't know why I can't initialize the bit filed in union.
Note that if the type of variable b is long or int, it can be initialized as expected.

**Comment by carlopi** [comment] 2022-07-15 04:16
Thanks for opening the issue, I do reproduce the bug.

**Comment by alexp-sssup** [comment] 2023-03-16 13:35
The problem is now fixed in Cheerp master

**Closed by alexp-sssup** 2023-03-16 13:35 UTC
Labels: compile_error
