### ISSUE TITLE
document.location instead of document.get_location()

### ISSUE THREAD

**Issue by uMaxmaxmaximus** [leaningtech/cheerp-meta#52] opened 2017-02-09 10:49 UTC
Why?
```c++
int webMain() {
    document.get_location()->set_href("//google.com"); // ugly
    document.location->set_href("//google.com"); // is better
    return 0;
}
```

**Comment by alexp-sssup** [comment] 2017-02-13 08:51
Arguably both get_something and set_something should be just .something. The problem is that at the LLVM level you have no information about the names of properties at the C++ level. We offer DOM interoperability by taking advantage of the fact that function names are instead preserved, we conventionally use the get_/set_ prefixes to distinguish between loads and stores in the backend. This may even be consider a feature, since often accessing a DOM property is actually more expensive than accessing a normal C++ class/struct member and the function call syntax is more expressive about the potential performance effect of the access.

**Comment by uMaxmaxmaximus** [comment] 2017-02-14 04:36
>  This may even be consider a feature, since often accessing a DOM property is actually more expensive than accessing a normal C++ class/struct member and the function call syntax is more expressive about the potential performance effect of the access.


actually is zero overhead, and compile `as is`

**Comment by uMaxmaxmaximus** [comment] 2017-02-14 07:04
You can use preprocessor to automatic replace

`document.body.innerHTML = "ololo";`

to 

`document.get_body()->set_innerHtml("ololo");`

No?

**Comment by alexp-sssup** [comment] 2017-02-14 07:30
I refer to the actual runtime performance of accessing DOM members, they do not necessarily behave like plain JS objects. For example accessing a DOM property might invoke a getter. Adding a special preprocessor would be an ad-hoc step that does not fit in the C++ programming model.

**Comment by uMaxmaxmaximus** [comment] 2017-02-15 18:35
Exist computer-oriented things.
Exist human-oriented things.

Programming languages must be human-oriented things.
We need to create a way to internal Cheerp problems did not seem programmer.

The fact that the LLVM has its limitations, but should be noticeable to the programmer. And it must be under the hood cheerp. To the programmer just do not notice them. Is not it so?

**Comment by carlopi** [comment] 2022-02-22 20:52
Hi @uMaxmaxmaximus and @cncmd, I just realized this can be build on top of Cheerp capabilities by generating wrappers around client objects like:

```
namespace newClient
{
struct HTMLElement
{
     client::HTMLElement* get();
}
struct Document
{
      client::Document* get();
      HTMLElement* body; 

      Document(client::Document* inner) : inner(inner), body(setUpAppropriateWrapper()) {}
}
}
```

I believe the current approach it's clearer and hide less things away (+ consistency it a nice to have), so I will close this as out of scope for the Cheerp project, but if anyone wants assistance in getting in getting this going I would be available.

**Closed by carlopi** 2022-02-22 20:52 UTC
