### ISSUE TITLE
/opt/cheerp/bin/clang-3.7 segfaults during compilation of libsodium-cmake

### ISSUE THREAD

**Issue by GeorgLippold** [leaningtech/cheerp-meta#31] opened 2016-05-05 23:44 UTC
I'm trying to compile libsodium-cmake (https://github.com/ctrix/libsodium-cmake) with cheerp, but clang crashes with segmentation fault 11:

Building C object src/libsodium/CMakeFiles/libsodium.dir/crypto_auth/hmacsha256/ref/hmac_hmacsha256.c.obj
clang-3.7: warning: argument unused during compilation: '-fno-strict-overflow'
0  clang-3.7                0x00000001008a7959 llvm::sys::PrintStackTrace(__sFILE*) + 57
1  clang-3.7                0x00000001008a80bb SignalHandler(int) + 395
2  libsystem_platform.dylib 0x00007fff9344052a _sigtramp + 26
3  clang-3.7                0x00000001005a37b5 llvm::ICmpInst::makeConstantRange(llvm::CmpInst::Predicate, llvm::APInt const&) + 309
4  clang-3.7                0x00000001002ccd79 llvm::SimplifyGEPInst(llvm::ArrayRef<llvm::Value*>, llvm::DataLayout const*, llvm::TargetLibraryInfo const*, llvm::DominatorTree const*, llvm::AssumptionCache*, llvm::Instruction const*) + 105
5  clang-3.7                0x00000001002ce64b llvm::SimplifyInstruction(llvm::Instruction*, llvm::DataLayout const*, llvm::TargetLibraryInfo const*, llvm::DominatorTree const*, llvm::AssumptionCache*) + 2203
6  clang-3.7                0x0000000100789148 (anonymous namespace)::EarlyCSE::runOnFunction(llvm::Function&) + 3912
7  clang-3.7                0x00000001005b1736 llvm::FPPassManager::runOnFunction(llvm::Function&) + 294
8  clang-3.7                0x00000001005b118d llvm::legacy::FunctionPassManagerImpl::run(llvm::Function&) + 189
9  clang-3.7                0x0000000100ccd604 clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::StringRef, llvm::Module*, clang::BackendAction, llvm::raw_ostream*) + 6836
10 clang-3.7                0x0000000100ddac32 clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) + 498
11 clang-3.7                0x000000010116ad24 clang::ParseAST(clang::Sema&, bool, bool) + 468
12 clang-3.7                0x0000000100aa6fee clang::FrontendAction::Execute() + 62
13 clang-3.7                0x0000000100a78d63 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) + 883
14 clang-3.7                0x0000000100ae02dd clang::ExecuteCompilerInvocation(clang::CompilerInstance*) + 3645
15 clang-3.7                0x000000010000934a cc1_main(llvm::ArrayRef<char const*>, char const*, void*) + 826
16 clang-3.7                0x0000000100006050 main + 1520
17 clang-3.7                0x00000001000059e4 start + 52
Stack dump:
0.	Program arguments: /opt/cheerp/bin/clang-3.7 -cc1 -triple cheerp--webbrowser -emit-llvm-bc -disable-free -disable-llvm-verifier -main-file-name hmac_hmacsha256.c -mrelocation-model static -mthread-model posix -relaxed-aliasing -fmath-errno -no-integrated-as -mconstructor-aliases -target-linker-version 136 -dwarf-column-info -coverage-file /Users/GLippold/development/libsodium-cmake/build/src/libsodium/CMakeFiles/libsodium.dir/crypto_auth/hmacsha256/ref/hmac_hmacsha256.c.obj -resource-dir /opt/cheerp/bin/../lib/clang/3.7.0 -D _FORTIFY_SOURCE=2 -I /Users/GLippold/development/libsodium-cmake/src/libsodium/include -I /Users/GLippold/development/libsodium-cmake/src/libsodium/include/sodium -I /Users/GLippold/development/libsodium-cmake/build/src/libsodium/include/sodium -internal-isystem /opt/cheerp/bin/../lib/clang/3.7.0/include -internal-externc-isystem /opt/cheerp/include -internal-externc-isystem /opt/cheerp/include/client -O3 -Wall -Wdiv-by-zero -Wextra -Winit-self -Wsometimes-uninitialized -Wstrict-prototypes -Wunused -Wwrite-strings -std=c99 -fconst-strings -fno-dwarf-directory-asm -fdebug-compilation-dir /Users/GLippold/development/libsodium-cmake/build/src/libsodium -ferror-limit 19 -fmessage-length 110 -fvisibility hidden -fwrapv -stack-protector 3 -mstackrealign -fno-rtti -fno-threadsafe-statics -fobjc-runtime=gcc -fdiagnostics-show-option -fcolor-diagnostics -vectorize-loops -vectorize-slp -o CMakeFiles/libsodium.dir/crypto_auth/hmacsha256/ref/hmac_hmacsha256.c.obj -x c /Users/GLippold/development/libsodium-cmake/src/libsodium/crypto_auth/hmacsha256/ref/hmac_hmacsha256.c 
1.	<eof> parser at end of file
2.	Per-function optimization
3.	Running pass 'Early CSE' on function '@crypto_auth_hmacsha256'
clang-3.7: error: unable to execute command: Segmentation fault: 11

Steps to reproduce:
0. Install cheerp-macosx-1.2.1 on OS X 10.11.4

1. checkout libsodium-cmake with git:

$ git clone https://github.com/ctrix/libsodium-cmake.git

2. create build folder in checked-out source and cd into it

$ cd libsodium-cmake
$ mkdir build
$ cd build

3. start cheerp compilation as per instructions

$ cmake -DCMAKE_TOOLCHAIN_FILE=/opt/cheerp/share/cmake/Modules/CheerpToolchain.cmake ..

4. start compilation

$ make

5. clang-3.7 crashes with above segfault.

The clang error message asked to submit the files hmac_hmacsha256-e4e734.{c,sh} with the bug report. I zipped them up and attached them to this bug report as [hmac_hmacsha256-e4e734.zip](https://github.com/leaningtech/cheerp-meta/files/251368/hmac_hmacsha256-e4e734.zip).

Thanks!

**Comment by GeorgLippold** [comment] 2016-05-30 22:46
Hi,
Are you even reading this bug tracker? 25 days and no acknowledgement / fix / anything. Project dead?

**Comment by alexp-sssup** [comment] 2016-05-31 07:00
Thanks for ping us again, this report slipped through. The issue is caused by pointer arithmetics with 64-bit offsets. A temporary workaround it to cast down offsets to 32-bit ints. For example, in the attached file:

```c++
  blocks(h,padded,64);
  blocks(h,in,inlen);
  in += (int)inlen;
  inlen &= 63;
  in -= (int)inlen;
```

**Comment by alexp-sssup** [comment] 2016-05-31 09:14
Issue fixed in git master

**Closed by alexp-sssup** 2016-05-31 09:14 UTC
